// Indiana 州立公园和森林完整数据
// 包含 26 个州立公园 + 15 个州立森林 = 41 个地点

import { StateData, Park } from "./states-data";

export const indianaData: StateData = {
  name: "Indiana",
  code: "IN",
  description: "Explore Indiana's diverse state parks and forests featuring stunning waterfalls, scenic lakes, towering sand dunes, and hardwood forests. From the iconic Indiana Dunes on Lake Michigan to the rugged hills of Brown County, discover endless outdoor adventures in the Hoosier State.",
  bounds: [[37.8, -88.1], [41.8, -84.8]],
  regions: [
    "Northern",
    "Central",
    "Eastern",
    "Southern",
    "Western"
  ],
  counties: [
    "Adams", "Allen", "Bartholomew", "Benton", "Blackford", "Boone", "Brown",
    "Carroll", "Cass", "Clark", "Clay", "Clinton", "Crawford", "Daviess",
    "Dearborn", "Decatur", "DeKalb", "Delaware", "Dubois", "Elkhart", "Fayette",
    "Floyd", "Fountain", "Franklin", "Fulton", "Gibson", "Grant", "Greene",
    "Hamilton", "Hancock", "Harrison", "Hendricks", "Henry", "Howard", "Huntington",
    "Jackson", "Jasper", "Jay", "Jefferson", "Jennings", "Johnson", "Knox",
    "Kosciusko", "LaGrange", "Lake", "LaPorte", "Lawrence", "Madison", "Marion",
    "Marshall", "Martin", "Miami", "Monroe", "Montgomery", "Morgan", "Newton",
    "Noble", "Ohio", "Orange", "Owen", "Parke", "Perry", "Pike", "Porter",
    "Posey", "Pulaski", "Putnam", "Randolph", "Ripley", "Rush", "St. Joseph",
    "Scott", "Shelby", "Spencer", "Starke", "Steuben", "Sullivan", "Switzerland",
    "Tippecanoe", "Tipton", "Union", "Vanderburgh", "Vermillion", "Vigo",
    "Wabash", "Warren", "Warrick", "Washington", "Wayne", "Wells", "White", "Whitley"
  ],
  images: [
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
    "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
    "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
    "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800"
  ],
  parks: [
    // ============ 州立公园 (State Parks) ============
    {
      id: 1,
      name: "Indiana Dunes State Park",
      type: "State Park",
      description: "Iconic park on Lake Michigan featuring towering sand dunes reaching 200 feet high. Offers 3 miles of pristine beaches, 16 miles of hiking trails, and diverse ecosystems from beach to forest. One of Indiana's most visited parks.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Swimming", "Picnicking", "Birding", "Wildlife Watching"],
      latitude: 41.6593,
      longitude: -87.063,
      popularity: 10,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(219) 926-1952"
    },
    {
      id: 2,
      name: "Brown County State Park",
      type: "State Park",
      description: "Indiana's largest and most popular state park covering 15,776 acres of scenic hills and forests. Known as the 'Little Smokies' for stunning fall foliage. Features extensive trails, horseback riding, and mountain biking.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Horseback Riding", "Wildlife Watching"],
      latitude: 39.1464,
      longitude: -86.229,
      popularity: 10,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 988-6406"
    },
    {
      id: 3,
      name: "Turkey Run State Park",
      type: "State Park",
      description: "Famous for spectacular sandstone gorges carved by Sugar Creek. Features stunning slot canyons, ladders through rock passages, and scenic suspension bridge. One of Indiana's most unique geological treasures.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding"],
      latitude: 39.9189,
      longitude: -87.2045,
      popularity: 10,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 597-2635"
    },
    {
      id: 4,
      name: "Clifty Falls State Park",
      type: "State Park",
      description: "Spectacular park in Madison featuring four major waterfalls including 60-foot Clifty Falls. Offers rugged canyon trails, scenic overlooks of the Ohio River valley, and beautiful spring wildflowers.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Wildlife Watching"],
      latitude: 38.7551,
      longitude: -85.4212,
      popularity: 9,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 273-8885"
    },
    {
      id: 5,
      name: "Pokagon State Park",
      type: "State Park",
      description: "Beautiful northern Indiana park on Lake James and Snow Lake. Famous for the 1,780-foot refrigerated toboggan run in winter. Excellent year-round recreation with beaches, trails, and historic Potawatomi Inn.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Horseback Riding", "Wildlife Watching"],
      latitude: 41.7077,
      longitude: -85.0228,
      popularity: 9,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(260) 833-2012"
    },
    {
      id: 6,
      name: "Spring Mill State Park",
      type: "State Park",
      description: "Historic park featuring restored 1814 pioneer village with working grist mill. Includes Twin Caves boat tour, nature center, and beautiful spring-fed streams. Rich in history and natural beauty.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Wildlife Watching"],
      latitude: 38.7464,
      longitude: -86.4169,
      popularity: 9,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 849-3534"
    },
    {
      id: 7,
      name: "McCormick's Creek State Park",
      type: "State Park",
      description: "Indiana's first state park (1916) featuring scenic limestone canyons, waterfalls, and covered bridge. Offers excellent hiking with Wolf Cave Trail and Canyon Inn lodging. Popular for nature photography.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Swimming", "Picnicking", "Birding", "Wildlife Watching"],
      latitude: 39.298,
      longitude: -86.724,
      popularity: 9,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 829-2235"
    },
    {
      id: 8,
      name: "Chain O'Lakes State Park",
      type: "State Park",
      description: "Unique park featuring interconnected glacial lakes perfect for kayaking and canoeing. Offers 2,678 acres with excellent fishing, sandy beaches, and beautiful nature preserve. Popular family destination.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 41.3335,
      longitude: -85.3813,
      popularity: 8,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(260) 636-2654"
    },
    {
      id: 9,
      name: "O'Bannon Woods State Park",
      type: "State Park",
      description: "Large 26,000-acre forested park in southern Indiana offering extensive backcountry camping and horseback riding. Features scenic overlooks, diverse wildlife, and peaceful natural setting.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Horseback Riding", "Hunting"],
      latitude: 38.193,
      longitude: -86.2729,
      popularity: 8,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 738-8232"
    },
    {
      id: 10,
      name: "Lincoln State Park",
      type: "State Park",
      description: "Historic park where young Abraham Lincoln spent his formative years. Features Lincoln Living Historical Farm, beautiful Lake Lincoln, excellent camping, and interpretive programs about Lincoln's Indiana youth.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Wildlife Watching"],
      latitude: 38.1047,
      longitude: -86.9999,
      popularity: 8,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 937-4710"
    },
    {
      id: 11,
      name: "Tippecanoe River State Park",
      type: "State Park",
      description: "Scenic park along the Tippecanoe River offering excellent canoeing and kayaking. Features diverse ecosystems, historic sites, and abundant wildlife. Popular for family camping and river recreation.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Horseback Riding", "Wildlife Watching"],
      latitude: 41.0835,
      longitude: -86.5344,
      popularity: 8,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(574) 946-3213"
    },
    {
      id: 12,
      name: "Shades State Park",
      type: "State Park",
      description: "Rugged park along Sugar Creek featuring dramatic sandstone cliffs and deep ravines. Known as the sister park to Turkey Run with equally stunning geology. Offers challenging hiking and primitive camping.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding"],
      latitude: 39.9295,
      longitude: -87.0725,
      popularity: 8,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 435-2810"
    },
    {
      id: 13,
      name: "Fort Harrison State Park",
      type: "State Park",
      description: "Former military base transformed into urban park in Indianapolis. Features historic Fort Benjamin Harrison, golf course, mountain biking trails, and Fall Creek valley. Easily accessible outdoor recreation.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Picnicking", "Birding", "Horseback Riding"],
      latitude: 39.8684,
      longitude: -86.0193,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(317) 591-0904"
    },
    {
      id: 14,
      name: "Mounds State Park",
      type: "State Park",
      description: "Archaeologically significant park featuring 10 prehistoric earthworks built by Adena-Hopewell culture. Offers hiking trails along White River, nature center, and fascinating Native American history.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding"],
      latitude: 40.1011,
      longitude: -85.6204,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 642-6627"
    },
    {
      id: 15,
      name: "Versailles State Park",
      type: "State Park",
      description: "Beautiful park featuring 230-acre Versailles Lake surrounded by hardwood forest. Excellent fishing, boating, and mountain biking on extensive trail system. Peaceful setting in southeastern Indiana.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Horseback Riding", "Wildlife Watching"],
      latitude: 39.0856,
      longitude: -85.2532,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 689-6424"
    },
    {
      id: 16,
      name: "Potato Creek State Park",
      type: "State Park",
      description: "Modern park near South Bend featuring 327-acre Worster Lake. Excellent family camping, swimming beach, and extensive trail system. Popular for fishing and mountain biking.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Horseback Riding", "Wildlife Watching"],
      latitude: 41.5351,
      longitude: -86.3617,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(574) 656-8186"
    },
    {
      id: 17,
      name: "Prophetstown State Park",
      type: "State Park",
      description: "Newest state park near Lafayette featuring prairie restoration, farm interpretive center, and Wabash River access. Offers camping, aquatic center, and educational programs about native prairie ecosystems.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Hunting", "Wildlife Watching"],
      latitude: 40.5027,
      longitude: -86.8321,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 567-4919"
    },
    {
      id: 18,
      name: "Harmonie State Park",
      type: "State Park",
      description: "Peaceful park on Wabash River near historic New Harmony. Features excellent camping, swimming beach, and water recreation. Rich in Harmonist communal society history.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking"],
      latitude: 38.0903,
      longitude: -87.9456,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 682-4821"
    },
    {
      id: 19,
      name: "Summit Lake State Park",
      type: "State Park",
      description: "Tranquil park featuring 2,680 acres with 800-acre Summit Lake. Excellent bass fishing, camping, and swimming. Popular for bird watching and peaceful water recreation.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Mountain Biking", "Wildlife Watching"],
      latitude: 39.9667,
      longitude: -85.2833,
      popularity: 7,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 766-5873"
    },
    {
      id: 20,
      name: "Charlestown State Park",
      type: "State Park",
      description: "Unique park on former Indiana Army Ammunition Plant site. Features 14 miles of trails through diverse habitats, fossil collecting areas, and exceptional wildlife viewing. Still undergoing restoration.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Picnicking", "Birding", "Wildlife Watching"],
      latitude: 38.4305,
      longitude: -85.6279,
      popularity: 6,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 256-5600"
    },
    {
      id: 21,
      name: "Whitewater State Park",
      type: "State Park",
      description: "Scenic park featuring beautiful Whitewater River valley. Offers camping, fishing, and hiking through hardwood forest. Popular for horseback riding and peaceful nature experiences.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 39.6667,
      longitude: -84.9167,
      popularity: 6,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 458-5565"
    },
    {
      id: 22,
      name: "Shakamak State Park",
      type: "State Park",
      description: "Historic CCC-built park featuring three scenic lakes. Offers family camping, swimming beaches, and fishing. Popular for its peaceful setting and vintage park facilities.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding"],
      latitude: 39.1333,
      longitude: -87.2167,
      popularity: 6,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 665-2158"
    },
    {
      id: 23,
      name: "Richard Lieber State Park",
      type: "State Park",
      description: "Named after the father of Indiana state parks. Peaceful forest setting with primitive camping and horseback riding. Ideal for those seeking quiet outdoor recreation.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Birding", "Horseback Riding", "Hunting"],
      latitude: 39.4691,
      longitude: -86.8735,
      popularity: 6,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(765) 795-6079"
    },
    {
      id: 24,
      name: "Ouabache State Park",
      type: "State Park",
      description: "Family-friendly park featuring American bison herd. Offers camping, fishing, hiking trails, and nature center. Name pronounced 'Wabash' represents the river's historical French spelling.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Hiking", "Fishing", "Camping", "Picnicking"],
      latitude: 40.7205,
      longitude: -85.11,
      popularity: 6,
      hours: "Open daily: 7:00 AM - 11:00 PM",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(800) 457-8283"
    },
    {
      id: 25,
      name: "Falls of the Ohio State Park",
      type: "State Park",
      description: "Unique park featuring 390-million-year-old fossil beds - one of the world's largest exposed Devonian fossil beds. Interpretive center showcases prehistoric marine life and Ohio River history.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Hiking", "Fishing", "Boating", "Picnicking", "Birding"],
      latitude: 38.2725,
      longitude: -85.7609,
      popularity: 6,
      hours: "Open daily: 9:00 AM - 5:00 PM (Interpretive Center)",
      entryFee: "$7 per vehicle (IN residents), $12 per vehicle (out-of-state)",
      phone: "(812) 280-9970"
    },
    {
      id: 26,
      name: "White Oak State Fishing Area",
      type: "State Fishing Area",
      description: "Specialized fishing area offering boat launch and trails. Focused on providing quality fishing access for anglers seeking peaceful waters.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Hiking", "Fishing", "Boating"],
      latitude: 38.45,
      longitude: -86.35,
      popularity: 5,
      hours: "Open daily: Dawn to Dusk",
      entryFee: "Free",
      phone: "(812) 358-2160"
    },

    // ============ 州立森林 (State Forests) ============
    {
      id: 27,
      name: "Morgan Monroe State Forest",
      type: "State Forest",
      description: "Indiana's premier state forest covering 24,000 acres of beautiful hardwood forest. Features excellent camping, hiking, and horseback riding trails. Popular for mountain biking and hunting. Includes scenic Yellowwood Lake.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Picnicking", "Hunting", "Wildlife Watching"],
      latitude: 39.3463,
      longitude: -86.4248,
      popularity: 9,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(765) 342-4026"
    },
    {
      id: 28,
      name: "Yellowwood State Forest",
      type: "State Forest",
      description: "Scenic state forest featuring Yellowwood Lake and excellent backcountry camping opportunities. Named after the rare yellowwood tree. Offers peaceful hiking, fishing, and horseback riding through rolling hardwood forests.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Picnicking", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 39.1535,
      longitude: -86.4187,
      popularity: 8,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 988-4675"
    },
    {
      id: 29,
      name: "Harrison-Crawford State Forest",
      type: "State Forest",
      description: "Largest state forest in Indiana's knobs region featuring rugged terrain, caves, and scenic overlooks. Offers challenging hiking trails, backcountry camping, and excellent wildlife habitat. Popular for horseback riding.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Hiking", "Fishing", "Camping", "Picnicking", "Hunting"],
      latitude: 38.2008,
      longitude: -86.2551,
      popularity: 8,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 738-8232"
    },
    {
      id: 30,
      name: "Clark State Forest",
      type: "State Forest",
      description: "Historic 24,000-acre forest near Louisville with diverse recreation. Features Oak Ridge Lake, extensive trail system, and excellent camping. Popular for mountain biking, horseback riding, and family activities.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Picnicking", "Mountain Biking", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 38.5591,
      longitude: -85.7681,
      popularity: 8,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 294-4306"
    },
    {
      id: 31,
      name: "Martin County State Forest",
      type: "State Forest",
      description: "Expansive 7,000-acre forest in scenic southern Indiana. Features diverse hardwood ecosystems, excellent hunting, and peaceful hiking trails. Part of the Hoosier Hills region with rolling terrain.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Hiking", "Fishing", "Hunting", "Wildlife Watching"],
      latitude: 38.7001,
      longitude: -86.7556,
      popularity: 7,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 247-3491"
    },
    {
      id: 32,
      name: "Jackson-Washington State Forest",
      type: "State Forest",
      description: "Beautiful hardwood forest with diverse wildlife and scenic terrain. Features excellent hunting opportunities, hiking trails, and backcountry camping. Part of the southern Indiana hills region.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Hiking", "Fishing", "Camping", "Picnicking", "Hunting"],
      latitude: 38.8613,
      longitude: -86.0086,
      popularity: 7,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 358-2160"
    },
    {
      id: 33,
      name: "Pike State Forest",
      type: "State Forest",
      description: "Nearly 3,000-acre forest offering diverse recreation including camping, fishing, and hunting. Features Pike Lake with excellent bass fishing. Popular for horseback riding and hiking through scenic woodlands.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Picnicking", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 38.4121,
      longitude: -87.2676,
      popularity: 7,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 354-8508"
    },
    {
      id: 34,
      name: "Frances Slocum State Forest",
      type: "State Forest",
      description: "Scenic 2,300-acre forest surrounding Frances Slocum Lake. Named after the famous white woman who lived with Miami Indians. Excellent fishing, boating, and birding. Features nature center and hiking trails.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Hiking", "Fishing", "Boating", "Birding", "Horseback Riding", "Wildlife Watching"],
      latitude: 40.729,
      longitude: -85.9653,
      popularity: 7,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(765) 473-4342"
    },
    {
      id: 35,
      name: "Salamonie River State Forest",
      type: "State Forest",
      description: "Beautiful 850-acre forest along Salamonie River offering camping, swimming, and water recreation. Features beach access, hiking trails, and mountain biking. Popular for family camping and fishing.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Mountain Biking", "Horseback Riding", "Hunting"],
      latitude: 40.8094,
      longitude: -85.6905,
      popularity: 7,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(260) 782-0430"
    },
    {
      id: 36,
      name: "Ferdinand State Forest",
      type: "State Forest",
      description: "Charming 900-acre forest in scenic southern Indiana. Features Ferdinand Lake with swimming beach, camping, and excellent fishing. Popular for mountain biking and family recreation.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Boating", "Swimming", "Picnicking", "Mountain Biking", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 38.2631,
      longitude: -86.7928,
      popularity: 7,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 367-1524"
    },
    {
      id: 37,
      name: "Selmier State Forest",
      type: "State Forest",
      description: "Peaceful forest offering primitive camping, fishing, and hunting. Features scenic trails through hardwood forest. Popular for horseback riding and wildlife watching in a quiet natural setting.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Hiking", "Fishing", "Boating", "Swimming", "Horseback Riding", "Hunting", "Wildlife Watching"],
      latitude: 39.0326,
      longitude: -85.5998,
      popularity: 6,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 346-2953"
    },
    {
      id: 38,
      name: "Greene-Sullivan State Forest",
      type: "State Forest",
      description: "Reclaimed coal mining land transformed into beautiful forest. Features unique terrain with scenic lakes, excellent fishing, and diverse wildlife habitat. Popular for hunting and hiking.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Hiking", "Fishing", "Camping", "Picnicking", "Hunting"],
      latitude: 39.0446,
      longitude: -87.2596,
      popularity: 6,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 648-2810"
    },
    {
      id: 39,
      name: "Owen-Putnam State Forest",
      type: "State Forest",
      description: "Quiet forest offering primitive camping and hunting. Features scenic hiking trails through hardwood forest. Ideal for those seeking solitude and natural beauty.",
      image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800",
      activities: ["Hiking", "Camping", "Picnicking", "Hunting"],
      latitude: 39.3208,
      longitude: -86.8456,
      popularity: 6,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(765) 795-6079"
    },
    {
      id: 40,
      name: "Martin State Forest",
      type: "State Forest",
      description: "Scenic forest in southwest Indiana offering camping, hiking, and hunting. Features peaceful trails through diverse hardwood ecosystems. Popular for mountain biking and wildlife observation.",
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800",
      activities: ["Camping", "Hiking", "Fishing", "Picnicking", "Mountain Biking", "Hunting", "Wildlife Watching"],
      latitude: 38.7001,
      longitude: -86.7556,
      popularity: 6,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 247-3491"
    },
    {
      id: 41,
      name: "Spencer County State Forest",
      type: "State Forest",
      description: "Small forest offering basic hiking and camping. Features peaceful trails and fishing opportunities. Ideal for quiet outdoor recreation and wildlife watching.",
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800",
      activities: ["Hiking", "Fishing", "Wildlife Watching"],
      latitude: 38.0347,
      longitude: -86.9678,
      popularity: 5,
      hours: "Open year-round, 24 hours",
      entryFee: "Free",
      phone: "(812) 357-5535"
    }
  ]
};
