// Mapping of forest IDs to their nearest major cities
export const FOREST_NEAREST_CITIES: Record<string, string> = {
  // California
  "angeles": "Los Angeles",
  "cleveland": "San Diego",
  "eldorado": "Sacramento",
  "inyo": "Bishop",
  "klamath": "Yreka",
  "lassen": "Redding",
  "los-padres": "Santa Barbara",
  "mendocino": "Ukiah",
  "modoc": "Alturas",
  "plumas": "Quincy",
  "san-bernardino": "San Bernardino",
  "sequoia": "Porterville",
  "shasta-trinity": "Redding",
  "sierra": "Fresno",
  "six-rivers": "Eureka",
  "stanislaus": "Sonora",
  "tahoe": "Truckee",
  
  // Pacific Northwest
  "colville": "Spokane",
  "deschutes": "Bend",
  "fremont-winema": "Klamath Falls",
  "gifford-pinchot": "Vancouver",
  "malheur": "John Day",
  "mount-baker-snoqualmie": "Seattle",
  "mount-hood": "Portland",
  "ochoco": "Prineville",
  "okanogan": "Winthrop",
  "olympic": "Port Angeles",
  "rogue-river-siskiyou": "Medford",
  "siuslaw": "Eugene",
  "umatilla": "Pendleton",
  "umpqua": "Roseburg",
  "wallowa-whitman": "La Grande",
  "willamette": "Eugene",
  
  // Rocky Mountains
  "arapaho": "Boulder",
  "beaverhead-deerlodge": "Dillon",
  "bighorn": "Sheridan",
  "bitterroot": "Missoula",
  "boise": "Boise",
  "bridger-teton": "Jackson",
  "caribou-targhee": "Idaho Falls",
  "clearwater": "Orofino",
  "custer": "Billings",
  "flathead": "Kalispell",
  "gallatin": "Bozeman",
  "grand-mesa": "Grand Junction",
  "gunnison": "Gunnison",
  "helena": "Helena",
  "idaho-panhandle": "Coeur d'Alene",
  "kootenai": "Libby",
  "lewis-clark": "Great Falls",
  "lolo": "Missoula",
  "medicine-bow-routt": "Steamboat Springs",
  "nez-perce": "Grangeville",
  "payette": "McCall",
  "pike": "Colorado Springs",
  "rio-grande": "Del Norte",
  "roosevelt": "Fort Collins",
  "salmon-challis": "Salmon",
  "san-isabel": "Pueblo",
  "san-juan": "Durango",
  "sawtooth": "Sun Valley",
  "shoshone": "Cody",
  "white-river": "Aspen",
  
  // Southwest
  "apache-sitgreaves": "Show Low",
  "ashley": "Vernal",
  "carson": "Taos",
  "cibola": "Albuquerque",
  "coconino": "Flagstaff",
  "coronado": "Tucson",
  "dixie": "Cedar City",
  "fishlake": "Richfield",
  "gila": "Silver City",
  "humboldt-toiyabe": "Elko",
  "kaibab": "Williams",
  "lincoln": "Alamogordo",
  "manti-la-sal": "Moab",
  "prescott": "Prescott",
  "santa-fe": "Santa Fe",
  "tonto": "Phoenix",
  "uinta-wasatch-cache": "Salt Lake City",
  "uncompahgre": "Montrose",
  
  // Alaska
  "chugach": "Anchorage",
  "tongass": "Juneau",
  
  // Great Lakes
  "chequamegon-nicolet": "Rhinelander",
  "chippewa": "Grand Rapids",
  "hiawatha": "Marquette",
  "huron-manistee": "Cadillac",
  "ottawa": "Ironwood",
  "superior": "Duluth",
  
  // Northeast
  "allegheny": "Pittsburgh",
  "finger-lakes": "Ithaca",
  "green-mountain": "Rutland",
  "white-mountain": "Conway",
  
  // Southeast
  "apalachicola": "Tallahassee",
  "chattahoochee-oconee": "Atlanta",
  "cherokee": "Knoxville",
  "conecuh": "Andalusia",
  "croatan": "New Bern",
  "daniel-boone": "London",
  "francis-marion": "Charleston",
  "george-washington-jefferson": "Roanoke",
  "kisatchie": "Alexandria",
  "monongahela": "Elkins",
  "nantahala": "Asheville",
  "ocala": "Ocala",
  "osceola": "Lake City",
  "pisgah": "Asheville",
  "sumter": "Columbia",
  "talladega": "Birmingham",
  "tuskegee": "Tuskegee",
  "uwharrie": "Asheboro",
  "william-bankhead": "Jasper",
  
  // Great Plains
  "angelina": "Lufkin",
  "black-hills": "Rapid City",
  "davy-crockett": "Crockett",
  "nebraska": "Chadron",
  "sabine": "Hemphill",
  "sam-houston": "Huntsville",
  "samuel-mckelvie": "Valentine",
  
  // Midwest
  "hoosier": "Bloomington",
  "mark-twain": "Rolla",
  "shawnee": "Carbondale",
  "wayne": "Athens",
  
  // Mississippi
  "bienville": "Forest",
  "delta": "Rolling Fork",
  "desoto": "Hattiesburg",
  "holly-springs": "Holly Springs",
  "homochitto": "Meadville",
  "tombigbee": "Ackerman",
  
  // Other
  "el-yunque": "San Juan",
  "ouachita": "Hot Springs"
};
