// 国家公园地貌类型数据

const PARK_TERRAIN: Record<string, string> = {
  "acadia": "Coastal",
  "arches": "Desert",
  "badlands": "Desert",
  "big-bend": "Desert",
  "biscayne": "Coastal",
  "black-canyon-of-the-gunnison": "Canyon",
  "bryce-canyon": "Canyon",
  "canyonlands": "Canyon",
  "capitol-reef": "Canyon",
  "carlsbad-caverns": "Desert",
  "channel-islands": "Coastal",
  "congaree": "Forest",
  "crater-lake": "Volcanic",
  "cuyahoga-valley": "Forest",
  "death-valley": "Desert",
  "denali": "Mountain",
  "dry-tortugas": "Coastal",
  "everglades": "Coastal",
  "gateway-arch": "Forest",
  "glacier": "Mountain",
  "glacier-bay": "Coastal",
  "grand-canyon": "Canyon",
  "grand-teton": "Mountain",
  "great-basin": "Mountain",
  "great-sand-dunes": "Desert",
  "great-smoky-mountains": "Mountain",
  "guadalupe-mountains": "Mountain",
  "haleakala": "Volcanic",
  "hawaii-volcanoes": "Volcanic",
  "hot-springs": "Forest",
  "indiana-dunes": "Coastal",
  "isle-royale": "Coastal",
  "joshua-tree": "Desert",
  "katmai": "Coastal",
  "kenai-fjords": "Coastal",
  "kings-canyon": "Mountain",
  "kobuk-valley": "Mountain",
  "lake-clark": "Mountain",
  "lassen-volcanic": "Volcanic",
  "mammoth-cave": "Forest",
  "mesa-verde": "Canyon",
  "mount-rainier": "Mountain",
  "new-river-gorge": "Forest",
  "north-cascades": "Mountain",
  "olympic": "Coastal",
  "petrified-forest": "Desert",
  "pinnacles": "Mountain",
  "redwood": "Forest",
  "rocky-mountain": "Mountain",
  "saguaro": "Desert",
  "sequoia": "Mountain",
  "shenandoah": "Mountain",
  "theodore-roosevelt": "Desert",
  "virgin-islands": "Coastal",
  "voyageurs": "Forest",
  "white-sands": "Desert",
  "wind-cave": "Forest",
  "wrangell-st-elias": "Mountain",
  "yellowstone": "Volcanic",
  "yosemite": "Mountain",
  "zion": "Canyon",
};

export function getParkTerrain(parkId: string): string {
  return PARK_TERRAIN[parkId] || "Mountain";
}
